name: test

on:
  push:
  pull_request:
    branches:
      - main
    paths:
      - "*.go"
      - "internal/**.go"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: ~1.21
      - run: make test
